name: Rustdoc Auto-Deploy

on:
  push:
   branches:
   - main

permissions:
  contents: write

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  rustdoc:
    name: Auto-build rustdoc for the rp6lib crate and deploy to github pages
    if: github.repository == 'Pr0gm4n/rust-rp6lib'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      run: rustup update --no-self-update nightly

    - name: Build Documentation
      run: make doc-deploy

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: docs
        publish_dir: ./docs
